// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSc0RdgigSkarxj9r86rXK6DYESoWNMiw',
    appId: '1:518287408089:web:67eb0905abd05df9c237c8',
    messagingSenderId: '518287408089',
    projectId: 'my-ecommerce-app-091405',
    authDomain: 'my-ecommerce-app-091405.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-091405.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkiydF4nkVUjDZDMxP8-Q1xnBFaoSkVc',
    appId: '1:518287408089:android:b193abb9da66f67bc237c8',
    messagingSenderId: '518287408089',
    projectId: 'my-ecommerce-app-091405',
    storageBucket: 'my-ecommerce-app-091405.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSc0RdgigSkarxj9r86rXK6DYESoWNMiw',
    appId: '1:518287408089:web:71e29efc3a15e657c237c8',
    messagingSenderId: '518287408089',
    projectId: 'my-ecommerce-app-091405',
    authDomain: 'my-ecommerce-app-091405.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-091405.firebasestorage.app',
  );
}
